-- cart_items_table
create table
  public.carts_items_table (
    id bigint generated by default as identity,
    cart_id bigint null,
    potions_id bigint null,
    quantity integer null,
    constraint carts_items_table_pkey primary key (id),
    constraint carts_items_table_cart_id_fkey foreign key (cart_id) references carts_table (id) on update cascade on delete cascade,
    constraint carts_items_table_potions_id_fkey foreign key (potions_id) references potions_table (id)
  ) tablespace pg_default;
-- cart_table
create table
  public.carts_table (
    id bigint generated by default as identity,
    customer text null,
    constraint carts_table_pkey primary key (id)
  ) tablespace pg_default;
-- global_inventory
create table
  public.global_inventory (
    id integer generated by default as identity,
    num_red_ml integer null,
    gold integer null,
    num_blue_ml integer null,
    num_green_ml integer null,
    num_evil_ml integer null,
    constraint global_inventory_pkey primary key (id)
  ) tablespace pg_default;
-- potions_table
create table
  public.potions_table (
    id bigint generated by default as identity,
    inventory integer null,
    type text null,
    sku text null,
    cost integer null,
    name text null,
    constraint potions_table_pkey primary key (id)
  ) tablespace pg_default;
